[project]
name = "monopolyv3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.1",
    "fastapi>=0.114.0",
    "uvicorn>=0.23.0",
    "pydantic>=2.6.0",
]
